### ISSUE TITLE
Atlas on Cloudron

### ISSUE THREAD

**Issue by OrcVole** [Alumniminium/atlas#1]
Please support one-click deployment of Atlas so that ordinary people can easily deploy their own Gemini server.  
  
You already have a Docker, so the bulk of the hard work is already completed. 

Cloudron has a demo where you can see how easy it is to deploy.

There is a thread for Atlas here, where you could introduce yourself and ask any questions or find help.

https://cloudron.io
https://forum.cloudron.io/topic/9051/atlas-on-cloudron-full-featured-gemini-protocol-self-hosted-server-for-gemlogs

**Comment by acidus99** [comment]
@OrcVole is a bot/shill account. Their account history is just opening PRs on repos asking them to join Cloudron.io. Ignore this nonsense

**Comment by OrcVole** [comment]
acidus99 is wrong. Please go ahead and consider supporting Atlas on Cloudron. It would make it a lot easier for ordinary people to self-host.
