### ISSUE TITLE
Question: Active Development

### ISSUE THREAD

**Issue by Smeeth** [Alumniminium/atlas#5]
Is this repository still under active developement? Are you somewhere else?

**Comment by Alumniminium** [comment]
Yes and no. I've been way too busy with work the recent months to work on any private projects. That being  said, I use atlas for my own gemini site, so I'll find time sooner or later, especially now that things seem to slow down at work. If you have any bug reports I'll try to get them fixed asap, but don't expect new major features the next month or two.
